name: build

on:
  push:
    branches:
      - main

jobs:
    build_latex:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Set up Git repository
          uses: actions/checkout@v4
        - name: Compile LaTeX document
          uses: xu-cheng/latex-action@v3
          with:
            root_file: russian-cv.tex
        - name: Upload PDF file
          uses: actions/upload-artifact@v4
          id: artifact-upload-step
          with:
            name: PDF
            path: russian-cv.pdf
        - name: Compile LaTeX English document
          uses: xu-cheng/latex-action@v3
          with:
            root_file: english-cv.tex
        - name: Upload PDF English file
          uses: actions/upload-artifact@v4
          id: artifact-upload-step-2
          with:
            name: EnglishPDF
            path: english-cv.pdf